# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NWJiODI2NDhhZmZiZDIxYjcwNDBjMzk4NDY3Mzc5N2VjYzRhZDhiYzc4YjM0MzllMGY2NTYwMTRjOWVlZGQ2YjlhZmM1ZjJjMjk2YjViNmI0ZDJkZTczODU0YWU4NjhkMzkxZmM0OWM1MGQwYjQyNjJlZWU2ODViZWNlYjUxMTc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
